version: "3.4"
services:
    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    # https://hub.docker.com/_/postgres
    postgresql:
        container_name: db-sql
        image: postgres:12.5
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: vooosh
            POSTGRES_PASSWORD: admin
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_MULTIPLE_DATABASES: test
        volumes:
            # Persist data between up/down
            - postgresql:/var/lib/postgresql/data:delegated

            # When data volume is empty, start every scripts in folder in A-Z order
            - ./docker/postgres/:/docker-entrypoint-initdb.d/
        restart: unless-stopped

    pgweb:
        container_name: db-ui
        image: sosedoff/pgweb:0.11.7
        ports:
            - "8081:8081"
        environment:
            - VIRTUAL_HOST=pgweb.mledoux.fr
            - DATABASE_URL=postgres://vooosh:admin@postgresql:5432/vooosh?sslmode=disable
        depends_on:
            - postgresql
        restart: unless-stopped

volumes:
    nginx-proxy:
    postgresql:
    pgadmin:
