version: "3.4"
services:
    vooosh:
        build: .
        command: yarn workspace @vooosh/server start
        volumes:
            - .:/tmp/app
            - /opt/app/node_modules
        ports:
            - "{{PORT}}:{{PORT}}"
        environment:
            - PORT={{PORT}}
            - DEBUG=vooosh:*
            - NODE_ENV=production
            - DB_HOST=postgresql
            - DB_NAME={{DB_NAME}}
            - VIRTUAL_HOST={{VIRTUAL_HOST}}
        networks:
            - backend
networks:
    backend:
        external: true
