version: "3.4"
services:
    pgweb:
        container_name: db-ui
        image: sosedoff/pgweb:0.11.7
        ports:
            - "8081:8081"
        environment:
            - VIRTUAL_HOST=pgweb.mledoux.fr
            - DATABASE_URL=postgres://vooosh:admin@postgresql:5432/vooosh?sslmode=disable
        restart: unless-stopped
        networks:
            - backend

    vooosh:
        build: .
        command: yarn workspace @vooosh/server start
        volumes:
            - .:/tmp/app
            - /opt/app/node_modules
        ports:
            - "{{PORT}}:{{PORT}}"
        environment:
            - VIRTUAL_HOST={{VIRTUAL_HOST}}
            - SERVER_PORT={{PORT}}
            - DEBUG=vooosh:*
            - NODE_ENV=production
            - DB_HOST=postgresql
            - DB_NAME={{DB_NAME}}
        networks:
            - backend
networks:
    backend:
        external: true
