version: "3.4"
services:
    vooosh:
        build: .
        command: yarn workspace @vooosh/server start
        volumes:
            - .:/tmp/app
            - /opt/app/node_modules
        ports:
            - "8080:8080"
        environment:
            NODE_ENV: production
            DB_HOST: postgresql
            VIRTUAL_HOST: { { VIRTUAL_HOST } }
        networks:
            - backend
networks:
    backend:
        external: true
